version: "3"

services:
  front:
    container_name: shopping-cart
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3030:3000"

    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - shopping-cart-node-modules:/usr/src/app/node_modules

volumes:
  shopping-cart-node-modules:
